# Generated by Django 4.2.10 on 2024-05-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_useraccount_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='image',
        ),
    ]
