# Generated by Django 4.2.10 on 2024-05-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='adopted_by',
            new_name='adopter',
        ),
    ]
