# Generated by Django 4.2.10 on 2024-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_review_pet_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(upload_to='images/pet/'),
        ),
    ]
